# Generated by Django 3.0.5 on 2021-06-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_files_uploaded_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='filecategory',
            options={'verbose_name_plural': 'File Categories'},
        ),
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='filesubcategory',
            options={'verbose_name_plural': 'File Subcategories'},
        ),
        migrations.AlterField(
            model_name='filecategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filesubcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
